### ISSUE TITLE
Improve classification performance

### ISSUE THREAD

**Issue by yja1** [lubebul/GAIN#1]
I train a classification work use resnet50. if add "Attention Mining Loss" , can improve classification performance? 
in other words,  through "Attention Mining Loss" could extract  more robust feature ?

**Comment by rctzeng** [comment]
Well, this is a potentially good research question. 

As the authors of GAIN didn't mention about it (i.e. the classification score before/after adding Attention Mining Loss) in their paper and neither did I check it in my code. 
Also, remind that GAIN is not meant to boost classification performance, but to help the segmentation models give "more complete" masks.

So, you're asking whether GAIN has a side benefit of boosting classification score?

To me, it's hard to say. My point is that if you can classify a object correct by just looking at the most discriminant part of the image. Why bother forcing the model to look at larger area of the image?

If you are curious about it, just start a research project and I will be interested in your experimental results. :)
